robot_config:
  urdf_file: "robots/fr3/fr3.urdf.xacro"
  arm_id: "fr3"
  arm_prefix: "franka_right"
  gripper_type: "rh_p12_rn_a" # <franka_default|rh_p12_rn_a>
  arm_controller: "joint_impedance_controller" # <joint_impedance_controller|cartesian_impedance_controller>
  gripper_controller: "none"
  xyz: "-0.06 -0.585 0"
  rpy: "0 0 0"
  xyz_ee: "0 0 0.0025"
  rpy_ee: "0 0 -0.785398"
